package asmgen

import (
	"bytes"
	"strings"
	"testing"
)

func TestASMWriter(t *testing.T) {
	var buf bytes.Buffer
	aw := NewASMWriter(&buf)

	// Test basic instruction writing
	err := aw.WriteInstruction("LD", "A,#42", "Load constant")
	if err != nil {
		t.Fatalf("WriteInstruction failed: %v", err)
	}

	result := buf.String()
	expected := "\tLD\tA,#42\t\t; Load constant\n"
	if result != expected {
		t.Errorf("Expected %q, got %q", expected, result)
	}
}

func TestWriteDB(t *testing.T) {
	var buf bytes.Buffer
	aw := NewASMWriter(&buf)

	data := []byte{0x01, 0x02, 0x03, 0x04}
	err := aw.WriteDB(data, 2, "TestData", false)
	if err != nil {
		t.Fatalf("WriteDB failed: %v", err)
	}

	result := buf.String()
	lines := strings.Split(strings.TrimSpace(result), "\n")

	if !strings.Contains(lines[0], "TestData:") {
		t.Errorf("Expected label 'TestData:', got: %s", lines[0])
	}

	if !strings.Contains(result, "#01,#02") {
		t.Errorf("Expected data '#01,#02' in output: %s", result)
	}
}

func TestWriteHeader(t *testing.T) {
	var buf bytes.Buffer
	aw := NewASMWriter(&buf)

	err := aw.WriteHeader("v1.0", "Mode 0", 80, 200)
	if err != nil {
		t.Fatalf("WriteHeader failed: %v", err)
	}

	result := buf.String()
	if !strings.Contains(result, "; Generated by go-cpc-image") {
		t.Error("Expected header comment not found")
	}
	if !strings.Contains(result, "; Screen mode - Mode 0") {
		t.Error("Expected mode comment not found")
	}
	if !strings.Contains(result, "80x200") {
		t.Error("Expected size comment not found")
	}
}

func TestWriteDW(t *testing.T) {
	var buf bytes.Buffer
	aw := NewASMWriter(&buf)

	data := []uint16{0x1234, 0x5678, 0xABCD}
	err := aw.WriteDW(data, 3, "", true)
	if err != nil {
		t.Fatalf("WriteDW failed: %v", err)
	}

	result := buf.String()
	if !strings.Contains(result, "DW\t#1234,#5678,#ABCD") {
		t.Errorf("Expected word data in output: %s", result)
	}
	if !strings.Contains(result, "; Total size 3 words") {
		t.Error("Expected size comment not found")
	}
}