// Package asmgen provides Z80 assembly code generation utilities.
package asmgen

import (
	"fmt"
	"io"
	"strings"
	"time"
)

// ASMWriter wraps a writer and provides assembly generation utilities
type ASMWriter struct {
	w io.Writer
}

// NewASMWriter creates a new assembly writer
func NewASMWriter(w io.Writer) *ASMWriter {
	return &ASMWriter{w: w}
}

// WriteHeader writes the standard assembly file header
func (aw *ASMWriter) WriteHeader(version string, mode string, width, height int) error {
	if version != "" {
		if _, err := fmt.Fprintf(aw.w, "; Generated by go-cpc-image%s - %s\n",
			strings.ReplaceAll(version, "\n", " "), time.Now().Format("02/01/2006 (15 04 05)")); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprintf(aw.w, "; Screen mode - %s\n", mode); err != nil {
		return err
	}

	if width > 0 && height > 0 {
		if _, err := fmt.Fprintf(aw.w, "; Size (nbColsxNbRows) %dx%d\n", width, height); err != nil {
			return err
		}
	}

	return nil
}

// WriteLabel writes a label
func (aw *ASMWriter) WriteLabel(label string) error {
	if label != "" {
		_, err := fmt.Fprintf(aw.w, "%s:\n", label)
		return err
	}
	return nil
}

// WriteComment writes a comment line
func (aw *ASMWriter) WriteComment(comment string) error {
	_, err := fmt.Fprintf(aw.w, "; %s\n", comment)
	return err
}

// WriteInstruction writes an assembly instruction
func (aw *ASMWriter) WriteInstruction(op, operands, comment string) error {
	line := fmt.Sprintf("\t%s", op)
	if operands != "" {
		line += fmt.Sprintf("\t%s", operands)
	}
	if comment != "" {
		line += fmt.Sprintf("\t\t; %s", comment)
	}
	line += "\n"
	_, err := aw.w.Write([]byte(line))
	return err
}

// WriteOrg writes an ORG directive
func (aw *ASMWriter) WriteOrg(addr uint16) error {
	return aw.WriteInstruction("ORG", fmt.Sprintf("#%04X", addr), "")
}

// WriteRun writes a RUN directive
func (aw *ASMWriter) WriteRun(addr string) error {
	return aw.WriteInstruction("RUN", addr, "")
}

// WriteNoList writes a Nolist directive
func (aw *ASMWriter) WriteNoList() error {
	return aw.WriteInstruction("Nolist", "", "")
}

// WriteList writes a List directive
func (aw *ASMWriter) WriteList() error {
	return aw.WriteInstruction("List", "", "")
}

// WriteDB generates DB (define byte) directives for byte data
func (aw *ASMWriter) WriteDB(data []byte, lineLength int, label string, withSize bool) error {
	if label != "" {
		if err := aw.WriteLabel(label); err != nil {
			return err
		}
	}

	if len(data) == 0 {
		return nil
	}

	// Check if all bytes are the same value
	firstVal := data[0]
	sameVal := true
	for i := 1; i < len(data); i++ {
		if data[i] != firstVal {
			sameVal = false
			break
		}
	}

	if sameVal {
		// Use DS directive for repeated values
		if err := aw.WriteInstruction("DS", fmt.Sprintf("%d,#%02X", len(data), firstVal), ""); err != nil {
			return err
		}
	} else {
		// Generate DB lines
		for i := 0; i < len(data); i += lineLength {
			end := i + lineLength
			if end > len(data) {
				end = len(data)
			}

			var line strings.Builder
			line.WriteString("#")
			line.WriteString(fmt.Sprintf("%02X", data[i]))

			for j := i + 1; j < end; j++ {
				line.WriteString(",#")
				line.WriteString(fmt.Sprintf("%02X", data[j]))
			}

			if err := aw.WriteInstruction("DB", line.String(), ""); err != nil {
				return err
			}
		}
	}

	if withSize {
		if err := aw.WriteComment(fmt.Sprintf("Total size %d bytes", len(data))); err != nil {
			return err
		}
	}

	return nil
}

// WriteDW generates DW (define word) directives for word data
func (aw *ASMWriter) WriteDW(data []uint16, lineLength int, label string, withSize bool) error {
	if label != "" {
		if err := aw.WriteLabel(label); err != nil {
			return err
		}
	}

	if len(data) == 0 {
		return nil
	}

	for i := 0; i < len(data); i += lineLength {
		end := i + lineLength
		if end > len(data) {
			end = len(data)
		}

		var line strings.Builder
		line.WriteString("#")
		line.WriteString(fmt.Sprintf("%03X", data[i]))

		for j := i + 1; j < end; j++ {
			line.WriteString(",#")
			line.WriteString(fmt.Sprintf("%03X", data[j]))
		}

		if err := aw.WriteInstruction("DW", line.String(), ""); err != nil {
			return err
		}
	}

	if withSize {
		if err := aw.WriteComment(fmt.Sprintf("Total size %d words", len(data))); err != nil {
			return err
		}
	}

	return nil
}

// WriteDBWithLabels generates DB directives with labeled sections
func (aw *ASMWriter) WriteDBWithLabels(data []byte, lineLength, sectionLines int, labelPrefix string, withSize bool) error {
	if len(data) == 0 {
		return nil
	}

	lineCount := 0
	labelIndex := 0

	// Write initial label if prefix provided and section lines > 0
	if labelPrefix != "" && sectionLines > 0 {
		if err := aw.WriteLabel(fmt.Sprintf("%s%02d", labelPrefix, labelIndex)); err != nil {
			return err
		}
		labelIndex++
	}

	for i := 0; i < len(data); i += lineLength {
		end := i + lineLength
		if end > len(data) {
			end = len(data)
		}

		var line strings.Builder
		line.WriteString("#")
		line.WriteString(fmt.Sprintf("%02X", data[i]))

		for j := i + 1; j < end; j++ {
			line.WriteString(",#")
			line.WriteString(fmt.Sprintf("%02X", data[j]))
		}

		if err := aw.WriteInstruction("DB", line.String(), ""); err != nil {
			return err
		}

		lineCount++

		// Check if we need a new label
		if sectionLines > 0 && lineCount >= sectionLines && i < len(data)-lineLength {
			lineCount = 0
			if labelPrefix != "" {
				if err := aw.WriteLabel(fmt.Sprintf("%s%02d", labelPrefix, labelIndex)); err != nil {
					return err
				}
				labelIndex++
			}
		}
	}

	if withSize {
		if err := aw.WriteComment(fmt.Sprintf("Total size %d bytes", len(data))); err != nil {
			return err
		}
	}

	return nil
}

// WriteDWWithLabels generates DW directives with labeled sections
func (aw *ASMWriter) WriteDWWithLabels(data []uint16, lineLength, sectionLines int, labelPrefix string, withSize bool) error {
	if len(data) == 0 {
		return nil
	}

	lineCount := 0
	labelIndex := 0

	// Write initial label if prefix provided and section lines > 0
	if labelPrefix != "" && sectionLines > 0 {
		if err := aw.WriteLabel(fmt.Sprintf("%s%02d", labelPrefix, labelIndex)); err != nil {
			return err
		}
		labelIndex++
	}

	for i := 0; i < len(data); i += lineLength {
		end := i + lineLength
		if end > len(data) {
			end = len(data)
		}

		var line strings.Builder
		line.WriteString("#")
		line.WriteString(fmt.Sprintf("%03X", data[i]))

		for j := i + 1; j < end; j++ {
			line.WriteString(",#")
			line.WriteString(fmt.Sprintf("%03X", data[j]))
		}

		if err := aw.WriteInstruction("DW", line.String(), ""); err != nil {
			return err
		}

		lineCount++

		// Check if we need a new label
		if sectionLines > 0 && lineCount >= sectionLines && i < len(data)-lineLength {
			lineCount = 0
			if labelPrefix != "" {
				if err := aw.WriteLabel(fmt.Sprintf("%s%02d", labelPrefix, labelIndex)); err != nil {
					return err
				}
				labelIndex++
			}
		}
	}

	if withSize {
		if err := aw.WriteComment(fmt.Sprintf("Total size %d words", len(data))); err != nil {
			return err
		}
	}

	return nil
}

// WriteEquate writes an EQU directive
func (aw *ASMWriter) WriteEquate(name string, value interface{}) error {
	var valueStr string
	switch v := value.(type) {
	case int:
		valueStr = fmt.Sprintf("#%04X", v)
	case uint16:
		valueStr = fmt.Sprintf("#%04X", v)
	case string:
		valueStr = v
	default:
		valueStr = fmt.Sprintf("%v", v)
	}

	_, err := fmt.Fprintf(aw.w, "%s\tEQU\t%s\n", name, valueStr)
	return err
}

// WriteBlankLine writes a blank line
func (aw *ASMWriter) WriteBlankLine() error {
	_, err := aw.w.Write([]byte("\n"))
	return err
}

// WriteRawLine writes a raw line of text
func (aw *ASMWriter) WriteRawLine(line string) error {
	_, err := fmt.Fprintf(aw.w, "%s\n", line)
	return err
}